### ISSUE TITLE
cmake issue due to Qt6 update

### ISSUE THREAD

**Issue by fskaeh** [equalsraf/homebrew-neovim-qt#3]
Due to Qt update to v6, neovim-qt doesn't build anymore, even if I previously install and symlink qt5 (the neovim-qt install will still redownload the "qt" package which points to v6):

``` zsh
==> Installing equalsraf/neovim-qt/neovim-qt
==> cmake ..
Last 15 lines from /Users/xxx/Library/Logs/Homebrew/neovim-qt/01.cmake:

  Could not find a package configuration file provided by "Qt5Core" with any
  of the following names:

    Qt5CoreConfig.cmake
    qt5core-config.cmake

  Add the installation prefix of "Qt5Core" to CMAKE_PREFIX_PATH or set
  "Qt5Core_DIR" to a directory containing one of the above files.  If
  "Qt5Core" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/tmp/neovim-qt-20210303-31347-50esy3/neovim-qt-0.2.16/build/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/equalsraf/homebrew-neovim-qt/issues```

**Comment by fskaeh** [comment]
Got a temporary fix by editing the formula myself to change the qt dependency to
``` zsh
depends_on "qt5"
```

**Comment by gwerbin** [comment]
> Got a temporary fix by editing the formula myself to change the qt dependency to
> 
> ```shell
> depends_on "qt5"
> ```

This isn't just a temporary fix, it's the correct solution IMO (until @equalsraf comes along and tells us that Neovim-Qt now works with Qt 6). Another way to spell this would be `qt@5`. I have it working in my own tap here: https://github.com/gwerbin/homebrew-tap/blob/e0dfa7e42dc514a8e0bdb60698a05e5d8a2e4607/Formula/neovim-qt.rb

**Comment by equalsraf** [comment]
Cheers, thanks for the ping.

**Comment by equalsraf** [comment]
Merged, I was able to build this morning, thanks for reporting and providing the fix :D
